### ISSUE TITLE
[enhancement] Headless server should allow clients without the maps mod

### ISSUE THREAD

**Issue by cluelessperson** [credomane/FactorioMods_FactorioMaps#18]
I have a script that ssh es into the server and restarts the factorio service with the maps mod installed.

If you can make it so the server can allow clients to login WITHOUT the maps mod, this would make it easier for me to do daily snapshots. :)

**Comment by credomane** [comment]
Factorio absolutely requires that the server and clients all have identical mods. This is because of the deterministic design of Factorio. Nothing I can do about it. 

If you can ssh into the server why not just SCP a copy of the map locally, load it, and map it that way? Would be easier, I would think.

**Comment by cluelessperson** [comment]
Good point, I'll do that.
