### ISSUE TITLE
Incorrect Maths to determine Total Width and Total Height in generateMap.lua

### ISSUE THREAD

**Issue by DanielNagy** [credomane/FactorioMods_FactorioMaps#19]
Using Top Left X/Y of -377, -6145 and Bottom Right X/Y of 0, -5700 as an example, your maths concludes the variables inGameTotalWidth of 377, and inGameTotalHeigh of **11845**. 
The correct results should be 377, and **445**. 
You have to Minus the Bottom Right X/Y from Top Left X/Y to find out the width / height.

I've tested, and updated my local generateMap.lua to the following to reflect the fix required instead.

`local inGameTotalWidth = math.ceil(data.bottomRight.x - data.topLeft.x)`
`local inGameTotalHeight = math.ceil(data.bottomRight.y - data.topLeft.y)`

Also, to stop the FILE NOT FOUND messages due to missing jpg layer files, i've also updated the following lines. Please note, I have only tested with "Huge" grid size setting.
As you zoom in however, it crops the edges off (still has the zoom level detail based on your Top Left / Bottom right co-ords)

`        --for y = 0, numVScreenshots - 1 do`
to
`        for y = -1, numVScreenshots do`

and

`            --for x = 0, numHScreenshots - 1 do`
to 
`                for x = -1, numHScreenshots do`

**Comment by credomane** [comment]
Fixed in FactorioMaps 0.16.1. Will release it on mod portal later once I test a bit more. Grab it from [here](https://github.com/credomane/FactorioMods_FactorioMaps/releases/latest) if you want it now.

Not sure what these FILE NOT FOUND messages are about. Did these happen so show up after you made the changes to calculating the inGameTotalWidth and inGameTotalHeight?
